### ISSUE TITLE
Wheel 3.9

### ISSUE THREAD

**Issue by firstcryptoman** [zebra-lucky/python-bls#1]
Hi, can you add a wheel for python versions 3.9 and higher, or if the repository is not supported, give me advice on how to do this?

**Comment by zebra-lucky** [comment]
Hello!

I'm sorry, I'll try to add 3.9, 3.10 on a week.

**Comment by zebra-lucky** [comment]
Build was done in the github action:

https://github.com/zebra-lucky/python-bls/blob/master/.github/workflows/build_wheels.yml

**Comment by firstcryptoman** [comment]
Thanks
